### ISSUE TITLE
Swift 3 compilation error for ResourceOperation 

### ISSUE THREAD

**Issue by jaythrash** [lucianomarisi/LoadIt#1]
Under Xcode 8 with Swift 3, compiling ResourceOperation.swift yields the following error message:

`<unknown>:0: error: same-type constraint type 'τ_0_0.Resource' does not conform to required protocol 'ResourceType'`

**Comment by lucianomarisi** [comment]
Swift 3 is not supported in this repository. Currently, I've moved the development of this project to this repository https://github.com/theappbusiness/TABResourceLoader so that more people will be able to maintain the project.
