### ISSUE TITLE
Same-type constraint type 'τ_0_0.Resource' does not conform to required protocol 'ResourceType'

### ISSUE THREAD

**Issue by Ramshandilya** [lucianomarisi/LoadIt#2]
I get this compiler error  
> <unknown>:0: error: same-type constraint type 'τ_0_0.Resource' does not conform to required protocol 'ResourceType'

after migrating to Swift 3.0.

**Comment by lucianomarisi** [comment]
Swift 3 is not supported in this repository. Currently, I've moved the development of this project to this repository https://github.com/theappbusiness/TABResourceLoader so that more people will be able to maintain the project.

**Comment by Ramshandilya** [comment]
Thanks for pointing to the repo. You should update it in your blog.
Great work btw!
